const catalogMaterials = [
  {
    name: "OPC Cement",
    aliases: ["cement", "opc", "simba cement", "portland cement"],
    category: "Cement & Aggregates",
    unit: "bag",
    description: "Ordinary Portland cement, 50kg bag.",
    image_url: "",
  },
  {
    name: "PPC Cement",
    aliases: ["ppc", "cement ppc", "pozzolana cement"],
    category: "Cement & Aggregates",
    unit: "bag",
    description: "Pozzolana Portland cement, 50kg bag.",
    image_url: "",
  },
  {
    name: "D8 Reinforcement Steel",
    aliases: ["d8", "8mm steel", "8mm rebar", "steel"],
    category: "Steel & Iron",
    unit: "bar",
    description: "8mm reinforcement bar for light structural works.",
    image_url: "",
  },
  {
    name: "D12 Reinforcement Steel",
    aliases: ["steel", "rebar", "d12", "reinforcement steel"],
    category: "Steel & Iron",
    unit: "bar",
    description: "12mm high-yield reinforcement bar.",
    image_url: "",
  },
  {
    name: "D16 Reinforcement Steel",
    aliases: ["d16", "16mm steel", "16mm rebar", "steel"],
    category: "Steel & Iron",
    unit: "bar",
    description: "16mm reinforcement bar for columns and beams.",
    image_url: "",
  },
  {
    name: "Binding Wire",
    aliases: ["binding wire", "wire", "steel wire"],
    category: "Steel & Iron",
    unit: "kg",
    description: "Annealed binding wire for tying reinforcement.",
    image_url: "",
  },
  {
    name: "River Sand",
    aliases: ["sand", "river sand", "building sand"],
    category: "Cement & Aggregates",
    unit: "tonne",
    description: "Washed construction sand.",
    image_url: "",
  },
  {
    name: "Ballast 20mm",
    aliases: ["ballast", "aggregate", "crushed stone"],
    category: "Cement & Aggregates",
    unit: "tonne",
    description: "20mm machine-cut aggregate.",
    image_url: "",
  },
  {
    name: "Machine Cut Stones",
    aliases: ["stones", "machine cut stones", "building stones"],
    category: "Cement & Aggregates",
    unit: "piece",
    description: "Standard machine-cut walling stones.",
    image_url: "",
  },
  {
    name: "2x4 Timber",
    aliases: ["timber", "wood", "2x4", "treated timber"],
    category: "Timber & Wood",
    unit: "metre",
    description: "Treated construction timber.",
    image_url: "",
  },
  {
    name: "Iron Sheet Gauge 30",
    aliases: ["roofing", "iron sheet", "mabati", "gauge 30"],
    category: "Roofing",
    unit: "sheet",
    description: "Corrugated roofing sheet.",
    image_url: "",
  },
  {
    name: "PVC Pipe 2 inch",
    aliases: ["pipe", "pvc", "plumbing pipe"],
    category: "Plumbing",
    unit: "length",
    description: "2 inch PVC pipe for plumbing works.",
    image_url: "",
  },
  {
    name: "PPR Pipe 25mm",
    aliases: ["ppr", "ppr pipe", "water pipe"],
    category: "Plumbing",
    unit: "length",
    description: "25mm PPR pipe for hot and cold water supply.",
    image_url: "",
  },
  {
    name: "Electrical Cable 2.5mm",
    aliases: ["cable", "electrical cable", "2.5mm cable"],
    category: "Electrical",
    unit: "metre",
    description: "2.5mm single-core electrical cable.",
    image_url: "",
  },
  {
    name: "Wall Paint 20L",
    aliases: ["paint", "wall paint", "emulsion paint"],
    category: "Finishing",
    unit: "bucket",
    description: "20 litre interior and exterior wall paint.",
    image_url: "",
  },
  {
    name: "Ceramic Floor Tiles",
    aliases: ["tiles", "floor tiles", "ceramic tiles"],
    category: "Finishing",
    unit: "box",
    description: "Ceramic floor tiles, one square metre per box.",
    image_url: "",
  },
  {
    name: "Gypsum Board 9mm",
    aliases: ["gypsum", "gypsum board", "ceiling board"],
    category: "Finishing",
    unit: "sheet",
    description: "9mm gypsum board for ceiling and partition works.",
    image_url: "",
  },
];

const catalogSuppliers = [
  {
    user: {
      phone: "+254711000001",
      name: "Amina Wanjiku",
      county: "nairobi",
    },
    supplier: {
      code: "BM01",
      business_name: "BuildMart Nairobi",
      registration_no: "BN-10291",
      county: "nairobi",
      town: "Industrial Area",
      location_lat: -1.3072,
      location_lng: 36.8511,
      delivery_radius_km: 35,
      delivery_days: ["mon", "tue", "wed", "thu", "fri", "sat"],
      min_order_value: 5000,
      delivery_fee_type: "per_km",
      delivery_fee: 120,
      payment_methods: ["cash_on_delivery", "mobile_money", "bank_transfer"],
      rating: 4.7,
      total_orders: 178,
      is_active: true,
    },
    products: [
      { material: "OPC Cement", price: 720, stock_qty: 420, min_order_qty: 1, times_queried_week: 26 },
      { material: "PPC Cement", price: 690, stock_qty: 300, min_order_qty: 1, times_queried_week: 14 },
      { material: "D12 Reinforcement Steel", price: 910, stock_qty: 950, min_order_qty: 10, times_queried_week: 12 },
      { material: "River Sand", price: 2600, stock_qty: 75, min_order_qty: 1, times_queried_week: 7 },
      { material: "Iron Sheet Gauge 30", price: 690, stock_qty: 310, min_order_qty: 5, times_queried_week: 9 },
      { material: "Wall Paint 20L", price: 3250, stock_qty: 90, min_order_qty: 1, times_queried_week: 5 },
    ],
  },
  {
    user: {
      phone: "+254711000002",
      name: "Peter Otieno",
      county: "nairobi",
    },
    supplier: {
      code: "PH02",
      business_name: "ProHardware Eastlands",
      registration_no: "BN-33812",
      county: "nairobi",
      town: "Donholm",
      location_lat: -1.3002,
      location_lng: 36.8919,
      delivery_radius_km: 25,
      delivery_days: ["mon", "tue", "wed", "thu", "fri"],
      min_order_value: 3000,
      delivery_fee_type: "flat",
      delivery_fee: 1500,
      payment_methods: ["cash_on_delivery", "mobile_money"],
      rating: 4.4,
      total_orders: 119,
      is_active: true,
    },
    products: [
      { material: "OPC Cement", price: 735, stock_qty: 260, min_order_qty: 1, times_queried_week: 18 },
      { material: "D8 Reinforcement Steel", price: 620, stock_qty: 720, min_order_qty: 10, times_queried_week: 8 },
      { material: "D12 Reinforcement Steel", price: 895, stock_qty: 600, min_order_qty: 10, times_queried_week: 17 },
      { material: "Ballast 20mm", price: 2850, stock_qty: 52, min_order_qty: 1, times_queried_week: 6 },
      { material: "PVC Pipe 2 inch", price: 460, stock_qty: 140, min_order_qty: 3, times_queried_week: 4 },
      { material: "Electrical Cable 2.5mm", price: 88, stock_qty: 2600, min_order_qty: 20, times_queried_week: 12 },
    ],
  },
  {
    user: {
      phone: "+254711000003",
      name: "Mercy Kilonzo",
      county: "kiambu",
    },
    supplier: {
      code: "KS03",
      business_name: "Kiambu Steel & Timber",
      registration_no: "BN-55217",
      county: "kiambu",
      town: "Ruiru",
      location_lat: -1.1466,
      location_lng: 36.9631,
      delivery_radius_km: 40,
      delivery_days: ["mon", "wed", "fri", "sat"],
      min_order_value: 4000,
      delivery_fee_type: "free_above_threshold",
      delivery_fee: 0,
      payment_methods: ["mobile_money", "bank_transfer"],
      rating: 4.6,
      total_orders: 92,
      is_active: true,
    },
    products: [
      { material: "OPC Cement", price: 745, stock_qty: 180, min_order_qty: 1, times_queried_week: 11 },
      { material: "D16 Reinforcement Steel", price: 1450, stock_qty: 420, min_order_qty: 10, times_queried_week: 9 },
      { material: "Binding Wire", price: 185, stock_qty: 350, min_order_qty: 5, times_queried_week: 6 },
      { material: "2x4 Timber", price: 145, stock_qty: 1200, min_order_qty: 20, times_queried_week: 8 },
      { material: "Machine Cut Stones", price: 58, stock_qty: 8500, min_order_qty: 100, times_queried_week: 13 },
    ],
  },
  {
    user: {
      phone: "+254711000004",
      name: "Njeri Mwangi",
      county: "mombasa",
    },
    supplier: {
      code: "CH04",
      business_name: "Coast Hardware Supplies",
      registration_no: "BN-74620",
      county: "mombasa",
      town: "Changamwe",
      location_lat: -4.0241,
      location_lng: 39.6245,
      delivery_radius_km: 45,
      delivery_days: ["mon", "tue", "wed", "thu", "fri", "sat"],
      min_order_value: 4500,
      delivery_fee_type: "flat",
      delivery_fee: 1800,
      payment_methods: ["cash_on_delivery", "mobile_money"],
      rating: 4.5,
      total_orders: 84,
      is_active: true,
    },
    products: [
      { material: "OPC Cement", price: 755, stock_qty: 380, min_order_qty: 1, times_queried_week: 16 },
      { material: "PPC Cement", price: 705, stock_qty: 260, min_order_qty: 1, times_queried_week: 10 },
      { material: "Ballast 20mm", price: 3000, stock_qty: 48, min_order_qty: 1, times_queried_week: 5 },
      { material: "Iron Sheet Gauge 30", price: 720, stock_qty: 220, min_order_qty: 5, times_queried_week: 8 },
      { material: "PPR Pipe 25mm", price: 520, stock_qty: 160, min_order_qty: 3, times_queried_week: 3 },
      { material: "Ceramic Floor Tiles", price: 1250, stock_qty: 140, min_order_qty: 2, times_queried_week: 7 },
    ],
  },
  {
    user: {
      phone: "+254711000005",
      name: "Samuel Kariuki",
      county: "kisumu",
    },
    supplier: {
      code: "LB05",
      business_name: "LakeBuild Depot",
      registration_no: "BN-88412",
      county: "kisumu",
      town: "Mamboleo",
      location_lat: -0.0722,
      location_lng: 34.7679,
      delivery_radius_km: 50,
      delivery_days: ["mon", "tue", "thu", "fri", "sat"],
      min_order_value: 3500,
      delivery_fee_type: "per_km",
      delivery_fee: 90,
      payment_methods: ["cash_on_delivery", "mobile_money", "bank_transfer"],
      rating: 4.3,
      total_orders: 61,
      is_active: true,
    },
    products: [
      { material: "OPC Cement", price: 740, stock_qty: 210, min_order_qty: 1, times_queried_week: 15 },
      { material: "D12 Reinforcement Steel", price: 920, stock_qty: 360, min_order_qty: 10, times_queried_week: 7 },
      { material: "River Sand", price: 2400, stock_qty: 68, min_order_qty: 1, times_queried_week: 10 },
      { material: "Machine Cut Stones", price: 54, stock_qty: 6200, min_order_qty: 100, times_queried_week: 11 },
      { material: "Gypsum Board 9mm", price: 980, stock_qty: 95, min_order_qty: 2, times_queried_week: 4 },
    ],
  },
  {
    user: {
      phone: "+254711000006",
      name: "Grace Chebet",
      county: "nakuru",
    },
    supplier: {
      code: "RV06",
      business_name: "Rift Valley Hardware",
      registration_no: "BN-92034",
      county: "nakuru",
      town: "Pipeline",
      location_lat: -0.3031,
      location_lng: 36.0800,
      delivery_radius_km: 55,
      delivery_days: ["mon", "tue", "wed", "fri", "sat"],
      min_order_value: 3800,
      delivery_fee_type: "flat",
      delivery_fee: 1200,
      payment_methods: ["cash_on_delivery", "mobile_money"],
      rating: 4.2,
      total_orders: 47,
      is_active: true,
    },
    products: [
      { material: "OPC Cement", price: 725, stock_qty: 240, min_order_qty: 1, times_queried_week: 13 },
      { material: "PPC Cement", price: 680, stock_qty: 180, min_order_qty: 1, times_queried_week: 9 },
      { material: "D8 Reinforcement Steel", price: 610, stock_qty: 500, min_order_qty: 10, times_queried_week: 6 },
      { material: "D16 Reinforcement Steel", price: 1420, stock_qty: 240, min_order_qty: 10, times_queried_week: 5 },
      { material: "2x4 Timber", price: 138, stock_qty: 900, min_order_qty: 20, times_queried_week: 8 },
      { material: "Wall Paint 20L", price: 3150, stock_qty: 55, min_order_qty: 1, times_queried_week: 3 },
    ],
  },
];

module.exports = { catalogMaterials, catalogSuppliers };

