const demoContractors = [
  {
    phone: "+254722100101",
    name: "Joseph Mwangi",
    county: "nairobi",
  },
  {
    phone: "+254733200202",
    name: "Wambui Maina",
    county: "kiambu",
  },
  {
    phone: "+254701300303",
    name: "Achieng Onyango",
    county: "kisumu",
  },
  {
    phone: "+254745400404",
    name: "Hassan Ali",
    county: "mombasa",
  },
  {
    phone: "+254700500505",
    name: "Brian Kiptoo",
    county: "nakuru",
  },
  {
    phone: "+254712600606",
    name: "Faith Nyambura",
    county: "nairobi",
  },
];

const demoOrders = [
  {
    id: 1201,
    contractor_phone: "+254722100101",
    supplier_code: "BM01",
    status: "pending",
    delivery_address: "Kasarani site, Nairobi",
    payment_method: "cash_on_delivery",
    payment_status: "unpaid",
    created_days_ago: 0,
    delivery_days_from_now: 1,
    items: [
      { material: "OPC Cement", quantity: 15 },
      { material: "River Sand", quantity: 1 },
    ],
  },
  {
    id: 1202,
    contractor_phone: "+254733200202",
    supplier_code: "KS03",
    status: "confirmed",
    delivery_address: "Ruiru bypass apartments",
    payment_method: "mobile_money",
    payment_status: "paid",
    created_days_ago: 1,
    delivery_days_from_now: 1,
    items: [
      { material: "Machine Cut Stones", quantity: 150 },
      { material: "Binding Wire", quantity: 10 },
    ],
  },
  {
    id: 1203,
    contractor_phone: "+254701300303",
    supplier_code: "LB05",
    status: "dispatched",
    delivery_address: "Mamboleo school project, Kisumu",
    payment_method: "mobile_money",
    payment_status: "paid",
    created_days_ago: 2,
    delivery_days_from_now: 0,
    items: [
      { material: "River Sand", quantity: 2 },
      { material: "Machine Cut Stones", quantity: 120 },
    ],
  },
  {
    id: 1204,
    contractor_phone: "+254745400404",
    supplier_code: "CH04",
    status: "delivered",
    delivery_address: "Nyali renovation site",
    payment_method: "bank_transfer",
    payment_status: "paid",
    created_days_ago: 4,
    delivery_days_from_now: -1,
    items: [
      { material: "Ceramic Floor Tiles", quantity: 5 },
      { material: "PPR Pipe 25mm", quantity: 6 },
    ],
  },
  {
    id: 1205,
    contractor_phone: "+254700500505",
    supplier_code: "RV06",
    status: "cancelled",
    delivery_address: "Pipeline estate, Nakuru",
    payment_method: "cash_on_delivery",
    payment_status: "unpaid",
    created_days_ago: 3,
    delivery_days_from_now: 2,
    items: [
      { material: "PPC Cement", quantity: 8 },
      { material: "2x4 Timber", quantity: 30 },
    ],
  },
  {
    id: 1206,
    contractor_phone: "+254712600606",
    supplier_code: "PH02",
    status: "rejected",
    delivery_address: "Donholm maisonette build",
    payment_method: "mobile_money",
    payment_status: "unpaid",
    created_days_ago: 2,
    delivery_days_from_now: 2,
    items: [
      { material: "D12 Reinforcement Steel", quantity: 10 },
      { material: "Electrical Cable 2.5mm", quantity: 30 },
    ],
  },
  {
    id: 1207,
    contractor_phone: "+254722100101",
    supplier_code: "BM01",
    status: "confirmed",
    delivery_address: "Kasarani site, Nairobi",
    payment_method: "mobile_money",
    payment_status: "pending",
    created_days_ago: 1,
    delivery_days_from_now: 2,
    items: [
      { material: "Iron Sheet Gauge 30", quantity: 12 },
      { material: "Wall Paint 20L", quantity: 2 },
    ],
  },
  {
    id: 1208,
    contractor_phone: "+254733200202",
    supplier_code: "BM01",
    status: "delivered",
    delivery_address: "Thindigua townhouse project",
    payment_method: "bank_transfer",
    payment_status: "paid",
    created_days_ago: 8,
    delivery_days_from_now: -5,
    items: [
      { material: "OPC Cement", quantity: 20 },
      { material: "D12 Reinforcement Steel", quantity: 15 },
    ],
  },
  {
    id: 1209,
    contractor_phone: "+254701300303",
    supplier_code: "LB05",
    status: "pending",
    delivery_address: "Kibuye market stalls",
    payment_method: "cash_on_delivery",
    payment_status: "unpaid",
    created_days_ago: 0,
    delivery_days_from_now: 3,
    items: [
      { material: "Gypsum Board 9mm", quantity: 8 },
      { material: "OPC Cement", quantity: 6 },
    ],
  },
  {
    id: 1210,
    contractor_phone: "+254700500505",
    supplier_code: "RV06",
    status: "dispatched",
    delivery_address: "Nakuru CBD shop fit-out",
    payment_method: "mobile_money",
    payment_status: "paid",
    created_days_ago: 2,
    delivery_days_from_now: 0,
    items: [
      { material: "D16 Reinforcement Steel", quantity: 10 },
      { material: "Wall Paint 20L", quantity: 2 },
    ],
  },
];

const demoSmsLogs = [
  {
    from_phone: "+254722100101",
    to_phone: "20880",
    message: "PRICE cement nairobi",
    direction: "in",
    message_type: "enquiry",
    status: "received",
    minutes_ago: 7,
  },
  {
    from_phone: "20880",
    to_phone: "+254722100101",
    message: "JengaLink Prices - OPC Cement (Nairobi)\n1. BM01 BuildMart Nairobi: KES 720/bag Delivery\n2. PH02 ProHardware Eastlands: KES 735/bag Delivery",
    direction: "out",
    message_type: "enquiry",
    status: "sent",
    minutes_ago: 6,
  },
  {
    from_phone: "+254722100101",
    to_phone: "20880",
    message: "ORDER BM01 15",
    direction: "in",
    message_type: "order",
    status: "received",
    minutes_ago: 5,
  },
  {
    from_phone: "20880",
    to_phone: "+254711000001",
    message: "New order #1201 from Joseph Mwangi for 15 bag OPC Cement, 1 tonne River Sand. Total: KES 13,400.",
    direction: "out",
    message_type: "order",
    status: "sent",
    minutes_ago: 4,
  },
  {
    from_phone: "+254733200202",
    to_phone: "20880",
    message: "STATUS 1202",
    direction: "in",
    message_type: "alert",
    status: "received",
    minutes_ago: 18,
  },
  {
    from_phone: "20880",
    to_phone: "+254701300303",
    message: "LakeBuild Depot has dispatched your order #1203. Reply STATUS 1203 anytime.",
    direction: "out",
    message_type: "alert",
    status: "sent",
    minutes_ago: 42,
  },
  {
    from_phone: "+254745400404",
    to_phone: "20880",
    message: "ALERT cement 700",
    direction: "in",
    message_type: "alert",
    status: "received",
    minutes_ago: 73,
  },
  {
    from_phone: "+254712600606",
    to_phone: "20880",
    message: "PRICE steel nairobi",
    direction: "in",
    message_type: "enquiry",
    status: "received",
    minutes_ago: 96,
  },
];

const demoPriceAlerts = [
  {
    contractor_phone: "+254745400404",
    material: "OPC Cement",
    target_price: 700,
    county: "mombasa",
    is_active: true,
  },
  {
    contractor_phone: "+254722100101",
    material: "D12 Reinforcement Steel",
    target_price: 880,
    county: "nairobi",
    is_active: true,
  },
  {
    contractor_phone: "+254700500505",
    material: "PPC Cement",
    target_price: 670,
    county: "nakuru",
    is_active: true,
  },
];

module.exports = { demoContractors, demoOrders, demoSmsLogs, demoPriceAlerts };

