const now = new Date().toISOString();

const seedData = {
  meta: {
    nextIds: {
      users: 8,
      suppliers: 4,
      materials: 9,
      supplier_products: 11,
      orders: 1001,
      order_items: 1,
      sms_logs: 1,
      price_alerts: 1,
      delivery_events: 1,
      sms_sessions: 1,
    },
  },
  users: [
    {
      id: 1,
      phone: "+254711000001",
      name: "Amina Wanjiku",
      role: "supplier",
      county: "nairobi",
      created_at: now,
      verified: true,
      otp_code: null,
      otp_expires: null,
    },
    {
      id: 2,
      phone: "+254711000002",
      name: "Peter Otieno",
      role: "supplier",
      county: "nairobi",
      created_at: now,
      verified: true,
      otp_code: null,
      otp_expires: null,
    },
    {
      id: 3,
      phone: "+254711000003",
      name: "Mercy Kilonzo",
      role: "supplier",
      county: "kiambu",
      created_at: now,
      verified: true,
      otp_code: null,
      otp_expires: null,
    },
    {
      id: 4,
      phone: "+254722000010",
      name: "Demo Contractor",
      role: "contractor",
      county: "nairobi",
      created_at: now,
      verified: true,
      otp_code: null,
      otp_expires: null,
    },
    {
      id: 5,
      phone: "+254733000100",
      name: "Admin User",
      role: "admin",
      county: "nairobi",
      created_at: now,
      verified: true,
      otp_code: null,
      otp_expires: null,
    },
    {
      id: 6,
      phone: "+254711000004",
      name: "Njeri Mwangi",
      role: "supplier",
      county: "mombasa",
      created_at: now,
      verified: true,
      otp_code: null,
      otp_expires: null,
    },
    {
      id: 7,
      phone: "+254711000005",
      name: "Samuel Kariuki",
      role: "supplier",
      county: "kisumu",
      created_at: now,
      verified: true,
      otp_code: null,
      otp_expires: null,
    },
  ],
  suppliers: [
    {
      id: 1,
      user_id: 1,
      code: "BM01",
      business_name: "BuildMart Nairobi",
      registration_no: "BN-10291",
      county: "nairobi",
      town: "Industrial Area",
      location_lat: -1.3072,
      location_lng: 36.8511,
      delivery_radius_km: 35,
      delivery_days: ["mon", "tue", "wed", "thu", "fri", "sat"],
      min_order_value: 5000,
      delivery_fee_type: "per_km",
      delivery_fee: 120,
      payment_methods: ["cash_on_delivery", "mobile_money", "bank_transfer"],
      rating: 4.7,
      total_orders: 178,
      is_active: true,
    },
    {
      id: 2,
      user_id: 2,
      code: "PH02",
      business_name: "ProHardware Eastlands",
      registration_no: "BN-33812",
      county: "nairobi",
      town: "Donholm",
      location_lat: -1.3002,
      location_lng: 36.8919,
      delivery_radius_km: 25,
      delivery_days: ["mon", "tue", "wed", "thu", "fri"],
      min_order_value: 3000,
      delivery_fee_type: "flat",
      delivery_fee: 1500,
      payment_methods: ["cash_on_delivery", "mobile_money"],
      rating: 4.4,
      total_orders: 119,
      is_active: true,
    },
    {
      id: 3,
      user_id: 3,
      code: "KS03",
      business_name: "Kiambu Steel & Timber",
      registration_no: "BN-55217",
      county: "kiambu",
      town: "Ruiru",
      location_lat: -1.1466,
      location_lng: 36.9631,
      delivery_radius_km: 40,
      delivery_days: ["mon", "wed", "fri", "sat"],
      min_order_value: 4000,
      delivery_fee_type: "free_above_threshold",
      delivery_fee: 0,
      payment_methods: ["mobile_money", "bank_transfer"],
      rating: 4.6,
      total_orders: 92,
      is_active: true,
    },
  ],
  materials: [
    {
      id: 1,
      name: "OPC Cement",
      aliases: ["cement", "opc", "simba cement", "portland cement"],
      category: "Cement & Aggregates",
      unit: "bag",
      description: "Ordinary Portland cement, 50kg bag.",
      image_url: "",
    },
    {
      id: 2,
      name: "PPC Cement",
      aliases: ["ppc", "cement ppc", "pozzolana cement"],
      category: "Cement & Aggregates",
      unit: "bag",
      description: "Pozzolana Portland cement, 50kg bag.",
      image_url: "",
    },
    {
      id: 3,
      name: "D12 Reinforcement Steel",
      aliases: ["steel", "rebar", "d12", "reinforcement steel"],
      category: "Steel & Iron",
      unit: "bar",
      description: "12mm high-yield reinforcement bar.",
      image_url: "",
    },
    {
      id: 4,
      name: "River Sand",
      aliases: ["sand", "river sand", "building sand"],
      category: "Cement & Aggregates",
      unit: "tonne",
      description: "Washed construction sand.",
      image_url: "",
    },
    {
      id: 5,
      name: "Ballast 20mm",
      aliases: ["ballast", "aggregate", "crushed stone"],
      category: "Cement & Aggregates",
      unit: "tonne",
      description: "20mm machine-cut aggregate.",
      image_url: "",
    },
    {
      id: 6,
      name: "2x4 Timber",
      aliases: ["timber", "wood", "2x4", "treated timber"],
      category: "Timber & Wood",
      unit: "metre",
      description: "Treated construction timber.",
      image_url: "",
    },
    {
      id: 7,
      name: "Iron Sheet Gauge 30",
      aliases: ["roofing", "iron sheet", "mabati", "gauge 30"],
      category: "Roofing",
      unit: "sheet",
      description: "Corrugated roofing sheet.",
      image_url: "",
    },
    {
      id: 8,
      name: "PVC Pipe 2 inch",
      aliases: ["pipe", "pvc", "plumbing pipe"],
      category: "Plumbing",
      unit: "length",
      description: "2 inch PVC pipe for plumbing works.",
      image_url: "",
    },
  ],
  supplier_products: [
    {
      id: 1,
      supplier_id: 1,
      material_id: 1,
      price: 720,
      stock_qty: 420,
      min_order_qty: 1,
      is_active: true,
      updated_at: now,
      times_queried_week: 26,
    },
    {
      id: 2,
      supplier_id: 2,
      material_id: 1,
      price: 735,
      stock_qty: 260,
      min_order_qty: 1,
      is_active: true,
      updated_at: now,
      times_queried_week: 18,
    },
    {
      id: 3,
      supplier_id: 3,
      material_id: 1,
      price: 745,
      stock_qty: 180,
      min_order_qty: 1,
      is_active: true,
      updated_at: now,
      times_queried_week: 11,
    },
    {
      id: 4,
      supplier_id: 1,
      material_id: 3,
      price: 910,
      stock_qty: 950,
      min_order_qty: 10,
      is_active: true,
      updated_at: now,
      times_queried_week: 12,
    },
    {
      id: 5,
      supplier_id: 2,
      material_id: 3,
      price: 895,
      stock_qty: 600,
      min_order_qty: 10,
      is_active: true,
      updated_at: now,
      times_queried_week: 17,
    },
    {
      id: 6,
      supplier_id: 3,
      material_id: 6,
      price: 145,
      stock_qty: 1200,
      min_order_qty: 20,
      is_active: true,
      updated_at: now,
      times_queried_week: 8,
    },
    {
      id: 7,
      supplier_id: 1,
      material_id: 4,
      price: 2600,
      stock_qty: 75,
      min_order_qty: 1,
      is_active: true,
      updated_at: now,
      times_queried_week: 7,
    },
    {
      id: 8,
      supplier_id: 2,
      material_id: 5,
      price: 2850,
      stock_qty: 52,
      min_order_qty: 1,
      is_active: true,
      updated_at: now,
      times_queried_week: 6,
    },
    {
      id: 9,
      supplier_id: 1,
      material_id: 7,
      price: 690,
      stock_qty: 310,
      min_order_qty: 5,
      is_active: true,
      updated_at: now,
      times_queried_week: 9,
    },
    {
      id: 10,
      supplier_id: 2,
      material_id: 8,
      price: 460,
      stock_qty: 140,
      min_order_qty: 3,
      is_active: true,
      updated_at: now,
      times_queried_week: 4,
    },
  ],
  orders: [],
  order_items: [],
  sms_logs: [],
  price_alerts: [],
  delivery_events: [],
  sms_sessions: [],
};

function cloneSeed() {
  return JSON.parse(JSON.stringify(seedData));
}

module.exports = { seedData, cloneSeed };

